# Site settings
title: Williams Bretagne
email: your-email@domain.com
description: "Association du Syndrome de Williams, région Bretagne."
baseurl: ""
url: "http://www.williams-bretagne.org"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
    - "bower_components"
    - "node_modules"
    - "bower.json"
    - "Gemfile"
    - "Gemfile.lock"
    - "Gruntfile.coffee"
    - "Gruntfile.coffee"
    - "LICENSE"
    - "package.json"
    - "Rakefile"
    - "README.md"
