# Site settings
title: Williams Bretagne
email: your-email@domain.com
description: "L'association Williams Bretagne regroupe de nombreuses familles de Bretagne, Normandie et Pays de la Loire. Son objectif est d'aider les personnes porteuses du syndrome de Williams ainsi que leur famille."
baseurl: ""
url: "http://www.williams-bretagne.org"

# Build settings
markdown: kramdown
permalink: pretty

exclude:
    - "bower_components"
    - "node_modules"
    - "bower.json"
    - "Gemfile"
    - "Gemfile.lock"
    - "Gruntfile.coffee"
    - "LICENSE"
    - "package.json"
    - "Rakefile"
    - "README.md"

include:
    - .nojekyll
